services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 'Your_password123'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    platform: linux/amd64
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      # NOTE the $$ to escape Compose interpolation
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -C -Q 'SELECT 1' > /dev/null 2>&1 || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' > /dev/null 2>&1 || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TinyDb;User=sa;Password=Your_password123;TrustServerCertificate=true;Encrypt=false
      - ApplyMigrations=true

volumes:
  db-data:
